# Uncomment this line to define a global platform for your project
platform :ios, '10.3'

target 'EmojiTransmitter' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmojiTransmitter
  pod 'Starscream', '~> 3.0'
  pod "SimpleLogger", :git => "https://github.com/thinkaboutiter/SimpleLogger.git", :tag => "1.1.3"

end
